NOT_SUBSTITUTABLE = "Not substitutable"
SUBSTITUTE_1 = "Substitute ((a gem))"
A_GEM = "Ruby"
SUBSTITUTE_1_SUBSTITUTED = "Substitute #{A_GEM}"
SUBSTITUTE_2 = "Substitute ((gem:a gem)) a ((gem))"
SUBSTITUTE_2_SUBSTITUTED = "Substitute #{A_GEM} a #{A_GEM}"
